### ISSUE TITLE
How to express year first seen

### ISSUE THREAD

**Issue by peterdesmet** [trias-project/alien-plants-belgium#2]
@qgroom @SoVDH @timadriaens @dimevil

The manual of alien plants has a column `FR` (first record?), which lists values like:

```
?
<1824
1976
ca. 1975
```

1. This information only makes sense when it is related to a region. However, this information is not available for `Fl`, `Br` and `Wa` separately, but generally (so assuming "Belgium"). The best way to then express that information is to add distribution records for "Belgium" in addition to the more detailed `Fl`, `Br` and `Wa` distribution regions:

```
Flanders: present
Wallonia: unknown
Belgium: present, firstRecord: 1996
```

2. The dataset also contains a column `MRR` (definition??), with years that are always later than `FR`. Is this "last seen"? Not sure what to do with this. It also contains values like:

```
Ann.
N
Nat.?
```

3. And finally, we'll need to think how to best express the firstRecordYear information. Most are a `YYYY` year, but there are some odd values and questionmarks too, which we might need to standardize? It basically boils down to how we want to use that information later on.

**Comment by qgroom** [comment]
Anywhere the MRR is Ann., N or Nat.? we can use the current year as the end of the period.

**Comment by timadriaens** [comment]
@peterdesmet you can always check definitions of the abbreviations in the manual [here](http://alienplantsbelgium.be/sites/alienplantsbelgium.be/files/tabel_2.pdf)

**Comment by timadriaens** [comment]
**First record (Abbrev.: FiR)**
Data about the first record of a given taxon are chiefly taken from the databased herbarium collections. No literature as such has been consulted as data from literature are not verifiable (see above). One major exception is made for some neophytes that a) were already present before 1900 and b) that usually have not been confused with related taxa. As old herbarium labels usually provide rather little information, for such taxa data were taken from De Wildeman & Durand (1899), except if certain herbarium collections predate this publication. Reliable data were obtained for instance for Geranium phaeum, Hepatica nobilis, Hesperis matronalis and many others. For others, for instance Solidago canadensis (widely confused with the related S. gigantea) or many taxa of Hieracium subgenus Pilosella, only verifiable data from the herbaria are taken into account.  As a rule, neophytes that already occurred prior to 1800 are indicated as “<1800” as their exact time of arrival usually is only estimative.  As a consequence the “first record” data usually indicate only the first time a given taxon was collected in Belgium. Some taxa were already naturalized the first time they were collected, others were only able to become naturalized (much) later or are still regarded as casuals. A particular issue is the escape (sexual or clonal  reproduction) of many formerly cultivated taxa. From the herbarium labels of such taxa it is not always
obvious whether a collection was taken from a cultivated or an escaped plant. As such, the exact time of escape of many cultivated taxa – even if fairly recent! – is not knowable. Examples are Aesculus hippocastanum, Castanea sativa, Juglans regia, Pinus spp., etc… This lack of information is compounded because escaped horticultural taxa formerly were often completely ignored and were not collected
at all. For such taxa there might be a considerable difference between the given and the real time of spontaneous occurrence.

**Comment by timadriaens** [comment]
**Most recent record (Abbrev.: ReR)**
Following Pyšek & al. (2004) the most recent record of a given taxon is also provided as this is considered to be an important piece of information. This enables us to select taxa that have only occurred recently and ignore taxa that have not been confirmed in, for instance, the past 50 or 100 years (or vice versa). For this item, herbarium sources were completed with field notes, essentially those of the author. Taxa that are widely naturalized – and that, theoretically, might be recorded every year – are indicated as such (**abbreviated: “N”**). Several ephemerous taxa (not naturalized) are rather or even very common (both locally or widely) and are also seen every year, at least in the past decade; such taxa are indicated as seen annually (**abbreviated: “Ann.”**).

**Comment by qgroom** [comment]
@timadriaens the question is whether we should use these dates for Flanders and Wallonia when we really only have the dates for the whole of Belgium. Filip thought is better not to include the present/absence data for the separate regions.

**Comment by timadriaens** [comment]
Obviously, no, that would be wrong in many cases (the more correct way would be to infer that date from the herbarium specimen the cross in the columns FL/WAL/BR refers to). We can infer the pres/abs per region from the occurrence records TrIAS will publish anyway.

**Comment by qgroom** [comment]
Yes, I hope I can get as much of the Belgian herbarium published to GBIF as possible.
